# Generated by Django 2.1.7 on 2019-04-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='administrador',
        ),
    ]
