# Generated by Django 2.1.7 on 2019-04-25 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alumno_docente_grupos_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='grupo',
        ),
    ]
