# Generated by Django 2.1.7 on 2019-04-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20190424_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='no_control',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
