# Generated by Django 2.1.7 on 2019-04-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20190424_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupos',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='grupos',
            name='hora',
        ),
        migrations.AddField(
            model_name='grupos',
            name='ciclo',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
