# Generated by Django 2.1.7 on 2019-04-25 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_alumno_grupoasignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='clavemateria',
        ),
        migrations.AddField(
            model_name='materia',
            name='claveMateria',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='grupoAsignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Grupos'),
        ),
    ]
