# Generated by Django 2.1.7 on 2019-04-25 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_auto_20190424_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reticula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_reticula', models.CharField(max_length=4)),
                ('cicloEscolar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciclo_Grupos', to='sistema.Grupos')),
                ('grupoAsignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupo_Grupos', to='sistema.Grupos')),
                ('materiaAsignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Materia')),
            ],
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='grupoAsignado',
        ),
    ]
