# Generated by Django 2.1.7 on 2019-05-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_auto_20190425_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reticula',
            name='anio_reticula',
        ),
        migrations.RemoveField(
            model_name='reticula',
            name='cicloEscolar',
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Reticula'),
        ),
        migrations.AddField(
            model_name='reticula',
            name='periodo',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='reticula',
            name='grupoAsignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupo_Grupos', to='sistema.Grupos'),
        ),
        migrations.AlterField(
            model_name='reticula',
            name='materiaAsignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Materia'),
        ),
    ]
