# Generated by Django 2.1.7 on 2019-05-07 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_auto_20190507_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='grupo',
        ),
        migrations.AddField(
            model_name='alumno',
            name='reticula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Reticula'),
        ),
        migrations.AlterField(
            model_name='reticula',
            name='grupoAsignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Grupos'),
        ),
        migrations.AlterField(
            model_name='reticula',
            name='materiaAsignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Materia'),
        ),
    ]
