# Generated by Django 2.1.7 on 2019-05-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0016_auto_20190513_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_rol',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registros.Usuario'),
        ),
        migrations.AlterField(
            model_name='reticula',
            name='grupoAsignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Grupos'),
        ),
        migrations.AlterField(
            model_name='reticula',
            name='materiaAsignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Materia'),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
