# Generated by Django 2.1.7 on 2019-05-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0017_auto_20190513_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reticula',
            name='grupoAsignado',
        ),
        migrations.RemoveField(
            model_name='reticula',
            name='materiaAsignada',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='reticula',
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='domicilio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='grupos',
        ),
        migrations.DeleteModel(
            name='materia',
        ),
        migrations.DeleteModel(
            name='Reticula',
        ),
    ]
