# Generated by Django 2.1.7 on 2019-05-13 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
        ('sistema', '0018_auto_20190513_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registros.Usuario'),
        ),
    ]
