# Generated by Django 2.1.7 on 2019-05-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0019_docente_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMateria', models.CharField(max_length=30)),
                ('clave', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
