# Generated by Django 2.1.7 on 2019-05-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0020_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Materia_grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Alumno', models.ManyToManyField(to='sistema.Alumno')),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='apellido_materno_docente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='apellido_paterno_docente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='materia_grupo',
            name='id_Docente',
            field=models.ManyToManyField(to='sistema.Docente'),
        ),
        migrations.AddField(
            model_name='materia_grupo',
            name='id_Materia',
            field=models.ManyToManyField(to='sistema.Materia'),
        ),
    ]
