# Generated by Django 2.1.7 on 2019-05-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0022_auto_20190523_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='mes',
            new_name='grupo',
        ),
        migrations.AddField(
            model_name='materia_grupo',
            name='id_Grupo',
            field=models.ManyToManyField(to='sistema.Grupo'),
        ),
        migrations.AlterField(
            model_name='materia_grupo',
            name='id_Alumno',
            field=models.ManyToManyField(to='sistema.Alumno'),
        ),
        migrations.AlterField(
            model_name='materia_grupo',
            name='id_Docente',
            field=models.ManyToManyField(to='sistema.Docente'),
        ),
    ]
