# Generated by Django 2.1.7 on 2019-05-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0024_auto_20190523_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='grupo',
            field=models.CharField(choices=[(7, 'A'), (8, 'B'), (9, 'C'), (10, 'D'), (11, 'E'), (12, 'F')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='materia_grupo',
            name='id_Alumno',
            field=models.ManyToManyField(to='sistema.Alumno'),
        ),
        migrations.AlterField(
            model_name='materia_grupo',
            name='id_Docente',
            field=models.ManyToManyField(to='sistema.Docente'),
        ),
    ]
