# Generated by Django 2.1.7 on 2019-05-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0025_auto_20190523_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='grado',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=4, max_length=1),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='grupo',
            field=models.CharField(choices=[(7, 'A'), (8, 'B'), (9, 'C'), (10, 'D'), (11, 'E'), (12, 'F')], default=1, max_length=4),
        ),
        migrations.AlterField(
            model_name='materia_grupo',
            name='id_Alumno',
            field=models.ManyToManyField(to='sistema.Alumno'),
        ),
        migrations.AlterField(
            model_name='materia_grupo',
            name='id_Docente',
            field=models.ManyToManyField(to='sistema.Docente'),
        ),
    ]
