# Generated by Django 2.1.7 on 2019-05-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0026_auto_20190523_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='grado',
            field=models.IntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='grupo',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='materia_grupo',
            name='id_Alumno',
            field=models.ManyToManyField(to='sistema.Alumno'),
        ),
        migrations.AlterField(
            model_name='materia_grupo',
            name='id_Docente',
            field=models.ManyToManyField(to='sistema.Docente'),
        ),
    ]
