# Generated by Django 2.1.7 on 2019-05-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0033_auto_20190523_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30, unique=True)),
                ('grado', models.IntegerField()),
                ('id_Materia', models.ManyToManyField(to='sistema.Materia')),
            ],
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='materia',
        ),
    ]
