# Generated by Django 2.1.7 on 2019-05-23 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0035_remove_grupo_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Plan_estudio'),
        ),
    ]
