# Generated by Django 2.1.7 on 2019-05-30 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0037_auto_20190523_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificación',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Alumno')),
            ],
        ),
        migrations.AlterField(
            model_name='plan_estudio',
            name='id_Materia',
            field=models.ManyToManyField(null=True, to='sistema.Materia'),
        ),
        migrations.AddField(
            model_name='calificación',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Plan_estudio'),
        ),
    ]
