# Generated by Django 2.1.7 on 2019-06-05 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0039_auto_20190530_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='plan_estudio',
            name='id_Materia',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='id_grupo',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='calificación',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='id_grupo',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='pin',
        ),
        migrations.AddField(
            model_name='calificación',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Materia'),
        ),
        migrations.AlterField(
            model_name='calificación',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Alumno'),
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='Plan_estudio',
        ),
    ]
