# Generated by Django 2.1.7 on 2019-06-05 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0040_auto_20190605_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo_escolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('finalizado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ciclo_escolar',
                'verbose_name_plural': 'ciclo_escolar',
            },
        ),
        migrations.CreateModel(
            name='Grados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('materias', models.ManyToManyField(to='sistema.Materia')),
            ],
            options={
                'verbose_name': 'grados',
                'verbose_name_plural': 'grados',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntuacion', models.IntegerField()),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('grado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Grados')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Materia')),
            ],
        ),
        migrations.RenameModel(
            old_name='Calificación',
            new_name='UnidadCalificada',
        ),
        migrations.DeleteModel(
            name='Ciclos',
        ),
        migrations.RenameField(
            model_name='unidadcalificada',
            old_name='valor',
            new_name='puntuacion_asignada',
        ),
        migrations.AlterField(
            model_name='unidadcalificada',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Alumno'),
        ),
    ]
