# Generated by Django 2.1.7 on 2019-07-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0042_auto_20190605_0030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ciclo_escolar',
        ),
        migrations.RemoveField(
            model_name='grados',
            name='materias',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='unidadcalificada',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='unidadcalificada',
            name='unidad',
        ),
        migrations.DeleteModel(
            name='Grados',
        ),
        migrations.DeleteModel(
            name='Unidad',
        ),
        migrations.DeleteModel(
            name='UnidadCalificada',
        ),
    ]
