# Generated by Django 2.1.7 on 2019-07-18 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0043_auto_20190717_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unidad', models.IntegerField()),
                ('Calificaion', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'verbose_name': 'alumnos', 'verbose_name_plural': 'alumnos'},
        ),
        migrations.AddField(
            model_name='alumno',
            name='grado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nivel_educativo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='grado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Alumno'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Materia'),
        ),
    ]
