# Generated by Django 2.1.7 on 2019-07-19 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0044_auto_20190718_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificaciones',
            options={'verbose_name': 'Calificaciones', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.RenameField(
            model_name='calificaciones',
            old_name='Calificaion',
            new_name='Calificacion',
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='grado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Alumno'),
        ),
    ]
