# Generated by Django 2.1.7 on 2019-08-02 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0048_auto_20190802_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoSecundaria',
            fields=[
                ('no_control', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=20, null=True)),
                ('nivel_educativo', models.CharField(blank=True, max_length=20, null=True)),
                ('grado', models.IntegerField(default=1)),
                ('telefono', models.CharField(max_length=10)),
                ('domicilio', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'alumnos',
                'verbose_name_plural': 'alumnos',
            },
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Alumno'),
        ),
    ]
