# Generated by Django 2.1.7 on 2019-08-02 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0049_auto_20190802_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionesSecundaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.IntegerField(default=1)),
                ('Unidad1', models.IntegerField(default=0)),
                ('Unidad2', models.IntegerField(default=0)),
                ('Unidad3', models.IntegerField(default=0)),
                ('Unidad4', models.IntegerField(default=0)),
                ('Unidad5', models.IntegerField(default=0)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.AlumnoSecundaria')),
            ],
            options={
                'verbose_name': 'Calificaciones',
                'verbose_name_plural': 'Calificaciones',
            },
        ),
        migrations.CreateModel(
            name='MateriaSecundaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMateria', models.CharField(max_length=30, unique=True)),
                ('clave', models.CharField(max_length=6, unique=True)),
                ('grado', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Alumno'),
        ),
        migrations.AddField(
            model_name='calificacionessecundaria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.MateriaSecundaria'),
        ),
    ]
