# Generated by Django 2.1.7 on 2019-08-03 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0053_auto_20190802_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.IntegerField(default=1)),
                ('Dia1', models.TimeField()),
                ('Dia2', models.TimeField()),
                ('Dia3', models.TimeField()),
                ('Dia4', models.TimeField()),
                ('Dia5', models.TimeField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Materia')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Alumno'),
        ),
    ]
