# Generated by Django 2.1.7 on 2019-08-05 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0055_auto_20190802_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocenteSecundaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDocente', models.CharField(max_length=100)),
                ('apellido_paterno_docente', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido_materno_docente', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(max_length=45)),
                ('telefono', models.IntegerField()),
                ('domicilio', models.CharField(max_length=50)),
                ('registro', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'DocenteSecundaria',
                'verbose_name_plural': 'DocentesSecundaria',
            },
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Alumno'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.DocenteSecundaria'),
        ),
    ]
